// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleDatabase.Data;

namespace VehicleWebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210614184119_Added more seed vehicles to database")]
    partial class Addedmoreseedvehiclestodatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleWebAPI.Models.InventoryVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 6000.0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Price = 21600.0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Price = 35400.0,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            Price = 35000.0,
                            VehicleId = 6
                        },
                        new
                        {
                            Id = 5,
                            Price = 7400.0,
                            VehicleId = 7
                        },
                        new
                        {
                            Id = 6,
                            Price = 2000.0,
                            VehicleId = 8
                        },
                        new
                        {
                            Id = 7,
                            Price = 7800.0,
                            VehicleId = 9
                        },
                        new
                        {
                            Id = 8,
                            Price = 14200.0,
                            VehicleId = 10
                        });
                });

            modelBuilder.Entity("VehicleWebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Authorization")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Authorization = 1,
                            Name = "Robert Muehler"
                        });
                });

            modelBuilder.Entity("VehicleWebAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Miles")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Silver",
                            Make = "Toyota",
                            Miles = 145000,
                            Model = "Corolla",
                            SellingPrice = 2000.0,
                            Status = 1,
                            UserId = 1,
                            VIN = "4Y1SL65848Z411439",
                            Year = 1997
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            Make = "Honda",
                            Miles = 145000,
                            Model = "Civic",
                            SellingPrice = 3000.0,
                            Status = 1,
                            UserId = 1,
                            VIN = "5Z1SL39746U411411",
                            Year = 1997
                        },
                        new
                        {
                            Id = 3,
                            Color = "Blue",
                            Make = "Subaru",
                            Miles = 175000,
                            Model = "Impreza",
                            SellingPrice = 4000.0,
                            Status = 1,
                            UserId = 1,
                            VIN = "7T1SL646726411440",
                            Year = 2005
                        },
                        new
                        {
                            Id = 4,
                            Color = "Red",
                            Make = "Mazda",
                            Miles = 200000,
                            Model = "3",
                            SellingPrice = 2000.0,
                            Status = 0,
                            UserId = 1,
                            VIN = "9P1SL658486268352",
                            Year = 2007
                        },
                        new
                        {
                            Id = 5,
                            Color = "Purple",
                            Make = "Mitsubishi",
                            Miles = 75000,
                            Model = "Eclipse",
                            SellingPrice = 6000.0,
                            Status = 2,
                            UserId = 1,
                            VIN = "YU1SL658486123463",
                            Year = 2005
                        },
                        new
                        {
                            Id = 6,
                            Color = "Blue",
                            Make = "Volkswagen",
                            Miles = 15600,
                            Model = "Rabbit",
                            SellingPrice = 35000.0,
                            Status = 1,
                            UserId = 1,
                            VIN = "WVWAA71K08W201030",
                            Year = 2015
                        },
                        new
                        {
                            Id = 7,
                            Color = "Black",
                            Make = "Ford",
                            Miles = 154000,
                            Model = "F250",
                            SellingPrice = 7400.0,
                            Status = 1,
                            UserId = 1,
                            VIN = "2FTHF25H6LCB36173",
                            Year = 1990
                        },
                        new
                        {
                            Id = 8,
                            Color = "White",
                            Make = "Acura",
                            Miles = 352000,
                            Model = "Integra",
                            SellingPrice = 2000.0,
                            Status = 1,
                            UserId = 1,
                            VIN = "JH4DA3341JS014654",
                            Year = 1988
                        },
                        new
                        {
                            Id = 9,
                            Color = "Beige",
                            Make = "Honda",
                            Miles = 98000,
                            Model = "CRV",
                            SellingPrice = 7800.0,
                            Status = 1,
                            UserId = 1,
                            VIN = "5J6RM4H75CL059384",
                            Year = 2012
                        },
                        new
                        {
                            Id = 10,
                            Color = "White",
                            Make = "Infiniti",
                            Miles = 42000,
                            Model = "G37",
                            SellingPrice = 14200.0,
                            Status = 1,
                            UserId = 1,
                            VIN = "JNKCV64E78M131002",
                            Year = 2008
                        });
                });

            modelBuilder.Entity("VehicleWebAPI.Models.VehicleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("VehicleWebAPI.Models.InventoryVehicle", b =>
                {
                    b.HasOne("VehicleWebAPI.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleWebAPI.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleWebAPI.Models.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleWebAPI.Models.VehicleImage", b =>
                {
                    b.HasOne("VehicleWebAPI.Models.Vehicle", null)
                        .WithMany("VehicleImages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleWebAPI.Models.User", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleWebAPI.Models.Vehicle", b =>
                {
                    b.Navigation("VehicleImages");
                });
#pragma warning restore 612, 618
        }
    }
}
