// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleDatabase.Data;

namespace VehicleDatabase.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Models.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<int>("Miles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.Property<double>("sellingPrice")
                        .HasColumnType("REAL");

                    b.HasKey("VIN");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VIN = "4Y1SL65848Z411439",
                            Color = "Silver",
                            ImageURI = "https://via.placeholder.com/150",
                            Make = "Toyota",
                            Miles = 145000,
                            Model = "Corolla",
                            Year = "1997",
                            sellingPrice = 2000.0
                        },
                        new
                        {
                            VIN = "5Z1SL65848A411439",
                            Color = "Black",
                            ImageURI = "https://via.placeholder.com/150",
                            Make = "Honda",
                            Miles = 145000,
                            Model = "Civic",
                            Year = "1997",
                            sellingPrice = 3000.0
                        },
                        new
                        {
                            VIN = "7T1SL658486411439",
                            Color = "Blue",
                            ImageURI = "https://via.placeholder.com/150",
                            Make = "Subaru",
                            Miles = 175000,
                            Model = "Impreza",
                            Year = "2005",
                            sellingPrice = 4000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
